// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn6zx_D8ewHqJNWc6mKvT9C7eQkidiH6E',
    appId: '1:826297019435:web:412f21e8acbba017f14e6e',
    messagingSenderId: '826297019435',
    projectId: 'chatapp-d62fc',
    authDomain: 'chatapp-d62fc.firebaseapp.com',
    storageBucket: 'chatapp-d62fc.appspot.com',
    measurementId: 'G-EY0DKNLH0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6oUde7Ug8oR3MryZ4IBpe6XrMAPduxCo',
    appId: '1:826297019435:android:9c044fa58105bb0af14e6e',
    messagingSenderId: '826297019435',
    projectId: 'chatapp-d62fc',
    storageBucket: 'chatapp-d62fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFb5zGvCBwP5viQhT2kSTE8XLb6I1PRGM',
    appId: '1:826297019435:ios:3cfcbb0e56595265f14e6e',
    messagingSenderId: '826297019435',
    projectId: 'chatapp-d62fc',
    storageBucket: 'chatapp-d62fc.appspot.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFb5zGvCBwP5viQhT2kSTE8XLb6I1PRGM',
    appId: '1:826297019435:ios:254d13791d56b5e0f14e6e',
    messagingSenderId: '826297019435',
    projectId: 'chatapp-d62fc',
    storageBucket: 'chatapp-d62fc.appspot.com',
    iosBundleId: 'com.example.chats.RunnerTests',
  );
}
